### PR TITLE
Remove hard dependency on BouncyCastle

### PR DESCRIPTION
**Pull request by solind**
I deactivate certain KeyType enum members when BouncyCastle is not registered, to prevent ClassNotFoundExceptions.

Also, I updated a log.error call in KeyExchanger to permit use with SFL4J 1.6.2.

Solves issue #478.

### CODE REVIEW

**Comment by solind** [comment]
Hey @hierynomus I'd love to add coverage for this change so that it would pass through the codecov hurdle, but ... I honestly have no idea how.  Ideally we'd need a way to run a test WITHOUT the BouncyCastle dependency in the classpath.  Care to provide me with a hint?

**Comment by hierynomus** [comment]
There are only `available` methods, which aren't being called anywhere. This PR seems incomplete still.
Furthermore, there are more places where the logging uses the SLF4j formatting, instead of `String.format`. I do not want to change that, `String.format` incurs a penalty, as that eagerly renders the formatted string.

**Comment by solind** [comment]
I eliminated String.format.  The ```available``` methods are called in the ```fromKey``` method, in KeyType line 409.

**Comment by solind** [comment]
I'm going to close this.  When we're done integrating the last set of changes, we'll create a new PR.

**Pull request closed without merging**
