### PR TITLE
Fix regression from 40f956b. Invalid length parameter.

### PR DESCRIPTION
**Pull request by dkocher**

### CODE REVIEW

**Comment by hierynomus** [comment]
Thanks @dkocher! I think this fixes #306. Good find totally missed that

**Comment by dkocher** [comment]
Would be nice if there is some test coverage that would catch this.

**Comment by hierynomus** [comment]
Agreed, do you have time to add a test? :)

**Comment by hierynomus** [comment]
I'll merge this for now and release a new release.

**Pull request merged**
