### PR TITLE
Allow sending CHANNEL_EOF message when ChannelOutputStream is closed

### PR DESCRIPTION
**Pull request by jpstotz**
As discussed in #553 it is sometimes necessary to send an CHANNEL_EOF message while in other situation it is redundant. 

Therefore the best solution in my opinion is to let the programmer choose if to send the CHANNEL_EOF message or not. Until now sending such a message requires some ugly hacks using reflection which is really bad. Therefore I implemented a new property that allows to enable sending an CHANNEL_EOF message when `close()` is called.

It is designed to be used in this way:

	final Command cmd = session.exec("cat");
	ChannelOutputStream out = (ChannelOutputStream) cmd.getOutputStream();
	out.setSignalCloseToRemote(true);
	out.write(data);
	out.close();

Note: I did not provide any additional unit tests as it is pretty complicated to write unit test that uses this feature and works on all common platforms (Linux, Window,s OSX, ...) as it requires an command to be executed that waits for stdin like `cat` or `tar x`. However not all platforms provide these commands by default, therefore the test would fail on at least one platform.

### CODE REVIEW

**Comment by jpstotz** [comment]
@hierynomus from my perspective this PR is now ready - feel free to comment or to criticize it.

As I wrote in my first post I don't see a good way to increase the code coverage because of the problems providing a platform independent unit test for this scenario.

**Comment by jpstotz** [comment]
If I understand it correctly also bug #496 is also about the inability to send the CHANNEL_EOF when the OutputStream is closed. Therefore by applying this PR this would make it possible "fix" this issue, too.

**Comment by hierynomus** [comment]
@jpstotz I'm hesitant to merge this in, as I think the reason I commented it out is that there is a race condition with closing sometimes. I would rather always send the EOF on the channel, which is allowed according to the spec. See in #143 for when this got commented out.

**Comment by jpstotz** [comment]
I am not sure what you mean with "race condition". The log of #143 does not contain many detailed error description. To me it is just a bunch of messages with works, works not, works again, works not... 

The only detailed description is [your post](https://github.com/hierynomus/sshj/issues/143#issuecomment-70799592) - but if I understand it correctly this error happened when the "line" was commented out - which means that no EOF was send, correct?

So the main question remains: Do you see the chance for a general solution? 

Because otherwise this workaround would at least to allow users to send EOF manually and therefore enable a lot of functionality which is currently unusable.

**Comment by hierynomus** [comment]
I've run a small test connecting 1000 times and doing a command. I've decided to re-implement the fix in #143 unconditionally, and if there is a new bug, we'll have a look at it. So this PR can be closed I think.

**Pull request closed without merging**
