### PR TITLE
Fix for issue #247: Allow mocking of SCPUploadClient and SCPDownloadClient

### PR DESCRIPTION
**Pull request by joprsal**
This change is to fix issue #247 

Summary of change:
- implementation classes renamed
  * SCPDownloadClient --> SCPDownloadClientImpl
  * SCPUploadClient --> SCPUploadClientImpl
- extracted interfaces (SCPDownloadClient & SCPUploadClient)
- made SCPFileTransfer use interfaces instead of implementation classes

Backwards compatibility note:
Since the new interfaces' names and public methods are exactly the same, existing code should not be affected.

### CODE REVIEW

**Comment by hierynomus** [comment]
Unfortunately that is not true. This requires that all code using sshj is
recompiled.
Op 17 mei 2016 14:51 schreef "Juraj Oprsal" <notifications@github.com>:

**Comment by joprsal** [comment]
Ok, my bad, you are right.

Would you accept a change to make those two classes non-final? Such change would not require existing code to be recompiled.

**Comment by hierynomus** [comment]
Agreed, let's make them non-final.

**Comment by joprsal** [comment]
Closing this pull request as rejected. Will raise a new one with agreed change.

**Pull request closed without merging**
