### PR TITLE
Attempt to fix race condition on SERVICE_ACCEPT (Fixes #559)

### LINKED ISSUE #559: Race condition in userauth.
We found a race condition with the way sshj is handling state transition.
Lib version: `v0.27.0`

Logs of incorrect behaviour are below, library has two threads serving connection. In logs they are marked with:
Application thread [A].
Reader thread [R].

Race is happening because reader keeps consuming messages while [A] is transitioning state (depending on a state we handle messages differently).
By default we handle messages with so called `NullService`, that sends `SSH_MSG_UNIMPLEMENTED` to the server for any message it tries to handle.

I tried to comment and highlight important parts of the logs.

// Initiating service transition  
[A] - Setting <> to 'null'
[A] - Sending SSH_MSG_SERVICE_REQUEST for ssh-userauth // Writing message  
[A] - Encoding packet `#4:` `<Request ssh-userauth>`
[A] - Awaiting <>  __// [A] waiting for [R] to notify it__
[R] - Received packet `#4:` `<SERVICE_ACCEPT ssh-userauth>`
[R] - Received packet SERVICE_ACCEPT  
[R] - Setting <> to `SOME` __// Notifying [A] (promise code)__
[R] - Received packet `#5:` `<SFTP BANNER HERE>`
[A] - Setting active service to ssh-userauth __// [A] woke and state transition happen__
[R] - Received packet USERAUTH_BANNER // Handled by __UserAuthService__ 
// Important piece of logs ends, normal flow below (started auth methods)
[A] - Setting <> to 'null'  
[A] - Trying 'none' auth...  
[A] - Encoding packet `#5:` `<AUTH MESSAGE>`
[A] - Awaiting <>  
  
// Initiating service transition  
[A] - Setting <> to 'null'
[A] - Sending SSH_MSG_SERVICE_REQUEST for ssh-userauth  
[A] - Encoding packet `#4:` `<Request ssh-userauth>`
[A] - Awaiting <>  
[R] - Received packet `#4:` `<SERVICE_ACCEPT ssh-userauth>`
[R] - Received packet SERVICE_ACCEPT  
[R] - Setting <> to `SOME` __// Notifying [A]__
[R] - Received packet `#5:` `<SFTP BANNER HERE>`
__// Issue below. We try to handle USERAUTH_BANNER before [A] woke up and transitioned to ssh-userauth service__
[R] - Received packet USERAUTH_BANNER __// No transition happened, so this will hit NullService, and lead to SSH_MSG_UNIMPLEMENTED__
[A] - Setting active service to ssh-userauth __// Now transition happened, but it's too late__
[R] - Sending SSH_MSG_UNIMPLEMENTED for packet `#5` __// from NullService__
[A] - Setting <> to 'null'
[R] - Encoding packet `#5:` `<...>` // Sending SSH_MSG_UNIMPLEMENTED about packet N5 (banner)  
// Auth service tries to initiate auth  
[A] - Trying 'none' auth...  
[A] - Encoding packet `#6:` `<AUTH MESSAGE>`
[A] - Awaiting <>  
// In the mean time, service got our SSH_MSG_UNIMPLEMENTED and decided to disconnect us.  
[R] - Received packet `#6:` `<…>` __// Server disconnects, as we told it that banner handling is not implemented__
[R] - Received packet DISCONNECT  
[R] - Received SSH_MSG_DISCONNECT (reason=PROTOCOL_ERROR, msg=Received a notification that a packet sent (packet `#5`) was not implemented by the remote peer).
[R] - Dying because - Received a notification that a packet sent (packet `#5`) was not implemented by the remote peer.
// END of the bug

### PR DESCRIPTION
**Pull request by hierynomus**

### CODE REVIEW

**Comment by hierynomus** [comment]
@xSeagullx Can you have a look to see whether this PR fixes the issue.

**Comment by xSeagullx** [comment]
Sure. Thank you! Will check in couple hours.

**Comment by xSeagullx** [comment]
Sorry, can't test right now (need to release stuff to test it, and can't do it right now), but will be back to you tomorrow.

Thank you for the fix (or rather an attempt at this point :) )!

**Comment by xSeagullx** [comment]
Issue seems to be fixed with the solution you propose! Thank you! I also see no side effects on other parts. 

Will you be releasing this soon?

**Pull request merged**
