### PR TITLE
Added support for RSA certificates as host key

### PR DESCRIPTION
**Pull request by aiwaniuk**
Added support to host verification using ssh-rsa-cert-v01@openssh.com host_key

### CODE REVIEW

**Comment by hierynomus** [comment]
Can you add a test with a certificate?

**Comment by aiwaniuk** [comment]
added test and removed dates check (I think this should be done at host_keyt verify phase)

**Comment by aiwaniuk** [comment]
@hierynomus any chance for review/merging it and two other PRs?

**Comment by hierynomus** [comment]
Yes, will try to have a look next week.

**Pull request merged**
