### PR TITLE
Integration test(s) with OpenSSH server in Docker

### PR DESCRIPTION
**Pull request by Igerly**
Hey!

Remember we were talking about this during summer - I've finally got around to do it! There aren't too many of the tests, but they seem to be working! :)

### CODE REVIEW

**Comment by Igerly** [comment]
Oh, and to run these locally I'm using:
- docker build -t sshj/test-sshd ./src/test/resources/
- docker run -p 2222:22 --name=sshj sshj/test-sshd
- And (at least as I'm working on a windows machine and my docker is being run from a VM) I need to specify  -DserverIP=xxx.xxx.xxx.xxx

**Comment by Igerly** [comment]
Hmm, that 3-rd build worked normally on my branch in Travis... Could you, perhaps, rerun the build?

**Comment by hierynomus** [comment]
Wow, thanks a lot! As for Travis, i think they had a hickup, there was a time out during dependency downloading.

**Comment by Igerly** [comment]
Thank you! It's really inspiring to see the work you're putting into this project.

**Pull request merged**
